name: seafood_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  random_string: ^2.3.1
  fluttertoast: ^8.2.8
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0

  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.0
  go_router: ^14.3.0
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  toastification: ^2.3.0
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  carousel_slider: ^5.0.0

  drift: ^2.21.0
  drift_flutter: ^0.2.1
  animate_do: ^2.0.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.3.3



dev_dependencies:


  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/

